name: reality_near
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.4+8 #Tiene que ir 1.0.1+5

environment:
  # sdk: ">=2.16.1 <3.0.0"
  # sdk: ">=2.16.1 <3.0.0"
    sdk: ">=2.7.0 <3.0.0"
dependencies:
  # mapbox_gl: ^0.16.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dotted_border: ^2.0.0+2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_chat_ui: ^1.5.8
  flutter_launcher_icons: ^0.9.2
  flutter_localizations:
    sdk: flutter
  flutter_map: ^2.0.0
  latlong2: ^0.8.1
  flutter_native_splash: ^2.1.6
  google_fonts: ^2.3.1
  http: ^0.13.4
  location: ^4.4.0
  logger: ^1.1.0
  near_flutter: ^0.0.1
  shared_preferences: ^2.0.15
  sizer: ^2.0.15
  url_launcher: ^6.1.0
  provider: ^6.0.3
  showcaseview: ^1.1.7
  qr_flutter: ^4.0.0
  qr_code_scanner: ^0.7.0
  loading_animation_widget: ^1.1.0+5
  screenshot: ^1.2.3
  # image_gallery_saver: ^1.7.1
  path_provider: ^2.0.11
  share_plus: ^4.0.10+1
  permission_handler: ^8.1.6
  upgrader: ^4.6.0
  # ar_flutter_plugin: ^0.6.4
  vector_math: any
  video_player: ^2.3.0
  socket_io_client: ^0.9.11

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: assets/imgs/Logo_sin_fondo.png
  color: "#eff4fa"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/iconLogo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/
    - assets/
    - assets/gift/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
